### ISSUE TITLE
Drop `python 3.9` support

### ISSUE THREAD

**Issue by jacobcook1995** [ImperialCollegeLondon/safedata_validator#120]
By making `python 3.10` our minimum supported version we can make use of its significantly cleaner supported typing notation. I don't see much reason to continue supporting a lower version given our very small user base

**Comment by davidorme** [comment]
> given our very small user base

Our _currently_ very small user base, so as to ease the adoption by our upcoming larger user base 😄

**Comment by jacobcook1995** [comment]
Oh yeah completely, this is like the definition of "easy to change now, nightmare to alter down the line" 😅
