### ISSUE TITLE
Fix issues with permit number

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/safedata_validator#123]
The `sdv` checking appears to crash when a permit authority is named but no number is provided. 

We need to:

- [ ] Verify this actually causes a crash
- [ ] Fix the crash
- [x] Add docs to say that missing permit numbers can simply use a null value of "Unknown" or similar.

**Comment by jacobcook1995** [comment]
I haven't been able to replicate the crash on mac, so is tricky to fix. I guess the documentation change is a good thing to do regardless though

**Comment by jacobcook1995** [comment]
Just tested this on windows and was unable to replicate the crash (it just gave a sensible "Permit number missing error"). I think something else was definitely going on and this issue should remain closed
