### ISSUE TITLE
Is taxon_index_to_text() used for anything?

### ISSUE THREAD

**Issue by jacobcook1995** [ImperialCollegeLondon/safedata_validator#15]
In the taxa.py script the following function is defined:
https://github.com/ImperialCollegeLondon/safedata_validator/blob/629fccb99bda005f92fd037f25f42909322bf4db/safedata_validator/taxa.py#L2789
It is then never called by any script within the `safedata_validator` packages, though maybe it is used by the website or `safedata`.

zenodo.py defines a similar seeming function:
https://github.com/ImperialCollegeLondon/safedata_validator/blob/629fccb99bda005f92fd037f25f42909322bf4db/safedata_validator/zenodo.py#L575

As far as I can make out the two functions have identical functionality aside for the fact that the first function allows text or html to be generated, while the second function only allows hmtl to be generated.

I feel like one function or the other should go, but am not sure which one?

**Comment by davidorme** [comment]
My mistake - I've solved the same problem twice. I think this belongs in `taxa.py` - it could applied to any taxon index, and I think the ability to use text as well is worthwhile. I'll merge and update.

**Comment by jacobcook1995** [comment]
Closed by #23
