### ISSUE TITLE
General read through + clean up of docs pre 3.0

### ISSUE THREAD

**Issue by jacobcook1995** [ImperialCollegeLondon/safedata_validator#48]
Before we publish 3.0 we should check that the docs build correctly. Then we should read through them and decide if any areas are not publication ready. If they are not then we should revise them

**Comment by davidorme** [comment]
Some points from Olivia:

> Do you want a list of projects that safedata_validator will be used for? Currently SAFE, Silwood and potentially Danum? 

Each of those is an independent deployment of the system - we don't need a list of those. Each deployment can optionally use project IDs to tag projects _within_ a deployment.

> And is it called the SAFE data system or safedata_validator? 

The "SAFE data system" are all three components - and `safedata_validator` is one of those, but we do need to make this clear.

> Finally what should the email contact be, is there one or will there be one for each project that data is collected from?

There will be one for each deployment - it would be good for that to be available somehow? Maybe in the `sdv` config and then stored in the metadata server and available via the API.
