### ISSUE TITLE
Problem in the resources API documentation

### ISSUE THREAD

**Issue by jacobcook1995** [ImperialCollegeLondon/safedata_validator#69]
There is a broken/outdated link in the API docs for Resources. Additionally, `CONFIGSPEC` gets displayed in a very messy way which we probably want to address.

See [here](https://safedata-validator.readthedocs.io/en/release-3.0.0/api/resources.html).

**Comment by davidorme** [comment]
Will be fixed in `feature/use_case_recipes`, which is now turning into a more general `mkdocs` update.
