### ISSUE TITLE
Edit docs to permit non NA taxon_name in morphospecies and functional groups

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/safedata_validator#77]
The docs say that NA should be used for the `taxon_name` field in the GBIFTaxa sheet for morphospecies and functional groups but this isn't enforced when the taxa are validated. 

However it isn't clear whether this really _matters_? The taxa will have a unique worksheet name and be descended from a valid taxon, so this value isn't used anywhere. Other non-backbone ranks (e.g. parvorder etc) do have meaningful (if unvalidated) `taxon_name` values.

**Comment by jacobcook1995** [comment]
Is there any checking that `taxon_name` matches the rank name in GBIF? I guess not because non-backbone ranks are not stored in GBIF? If there's no name validation this field will basically just be additional info, so I don't see any reason to force it to be NA really

**Comment by davidorme** [comment]
I agree - there are a few legacy datasets that provide that information and it is sensible information. Also the worksheet name is partly intended to act as an abbreviation. In the previous versions, the `taxon_name` was overwritten by the `worksheet_name` in the taxon index for morphospecies and functional groups but that seems like an error.

So, let's fix the docs not the behaviour.

**Comment by jacobcook1995** [comment]
Great I'll add it to my docs fix list!
