### ISSUE TITLE
Extent update fails if all entries invalid

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/safedata_validator#87]
The spatial and temporal extents are updated when validating fields containing temporal or spatial data. If _all_ the entries in that field are invalid (NA or not formatted correctly) then the code tries to take `min` and `max` of nothing and throws an error:

```python
  File "/Users/dorme/Research/SAFE/Database/safedata_validator_package/safedata_validator/field.py", line 2104, in validate_data
    self.min = min(data)
```

**Comment by jacobcook1995** [comment]
I don't think I made an issue for this but I believe that this issue is fixed by #83

**Comment by jacobcook1995** [comment]
The fix only exists on the `release/3.0.0` branch, not on the `develop` branch

**Comment by davidorme** [comment]
Aha - I'm running on `feature/docs_update`. Might that branch predate #83?

**Comment by davidorme** [comment]
OK - excellent. It looks like `GeoField` already handles this case but doesn't test the implementation, so I'll add a test for this and fix that.

**Comment by davidorme** [comment]
There's actually a downstream bug of this - `DatetimeField.report` fails if _all_ data are invalid because it tries to take the `.date` property of `None`. Will fix.
